---
- name: Installation et configuration de MySQL
  hosts: all
  become: yes
  vars:
    mysql_root_password: "SecurePass123!"
    app_db_name: "app_db"
    app_db_user: "appuser"
    app_db_password: "SecurePass123!"
  tasks:
    - name: Installer mysql-server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Assurer que le service MySQL est démarré
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Définir le mot de passe root MySQL
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        state: present

    - name: Créer la base de données app_db
      mysql_db:
        name: "{{ app_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur appuser avec tous les droits sur app_db
      mysql_user:
        name: "{{ app_db_user }}"
        password: "{{ app_db_password }}"
        priv: "{{ app_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"