---
- name: Correction installation MySQL
  hosts: databases
  become: yes
  tasks:
    - name: Installer apt-utils
      apt:
        name: apt-utils
        state: present
      ignore_errors: yes

    - name: Forcer la reconfiguration des paquets
      command: dpkg --configure -a
      register: dpkg_result
      ignore_errors: yes

    - name: Réinstaller MySQL Server
      apt:
        name: mysql-server
        state: present
      register: mysql_result
      ignore_errors: yes

    - name: Vérifier le statut du service MySQL
      command: systemctl status mysql
      register: mysql_status
      ignore_errors: yes

    - name: Afficher le résultat de dpkg
      debug:
        var: dpkg_result.stdout

    - name: Afficher le résultat de l'installation MySQL
      debug:
        var: mysql_result.stdout

    - name: Afficher le statut du service MySQL
      debug:
        var: mysql_status.stdout
