---
- name: Créer dossier des métriques
  file:
    path: /opt/metrics
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Déployer serveur de métriques (CPU/RAM)
  template:
    src: "../templates/metrics/metrics_server.py.j2"
    dest: "/opt/metrics/metrics_server.py"
    mode: "0755"

- name: Vérifier si le serveur de métriques tourne
  shell: pgrep -f "/opt/metrics/metrics_server.py" >/dev/null
  register: metrics_running
  changed_when: false
  failed_when: false

- name: Démarrer le serveur de métriques si nécessaire
  shell: nohup python3 /opt/metrics/metrics_server.py >/var/log/metrics_server.log 2>&1 &
  when: metrics_running.rc != 0
  async: 0
  poll: 0
