---
- name: Création des utilisateurs et installation des outils
  hosts: all
  become: yes

  vars:
    users:
      - webmaster
      - appuser
      - monitoring
    tools:
      - htop
      - curl
      - wget
      - vim
      - git
      - tree
    group_name: appgroup

  tasks:
    - name: Créer le groupe appgroup
      group:
        name: "{{ group_name }}"
        state: present

    - name: Créer les utilisateurs et les ajouter au groupe appgroup
      user:
        name: "{{ item }}"
        groups: "{{ group_name }}"
        append: yes
        state: present
      loop: "{{ users }}"

    - name: Installer les outils requis
      package:
        name: "{{ tools }}"
        state: present