---
- name: Déploiement Nginx avec rolling update
  hosts: web
  serial: 1
  gather_facts: yes

  tasks:
    - block:
        - name: Installer Nginx
          apt:
            name: nginx
            state: present
            update_cache: yes

        - name: Déployer nginx.conf
          template:
            src: "../templates/nginx/nginx.conf.j2"
            dest: "/etc/nginx/nginx.conf"
            mode: "0644"
          notify: Reload nginx

        - name: Redémarrer Nginx si nécessaire
          service:
            name: nginx
            state: started
            enabled: yes

    - name: Déployer service de métriques (CPU/RAM)
      import_tasks: metrics.yml

    - name: Inclure le déploiement du site stylé
      import_tasks: website.yml

    - name: Validation HTTP
      uri:
        url: "http://localhost"
        return_content: yes
      register: http_check
      retries: 5
      delay: 2
      until: http_check.status == 200

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
